ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'FINISHED';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'NEEDS_REWORK';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'NEEDS_REDESIGN';

ALTER TABLE "Project"
  ADD COLUMN IF NOT EXISTS "needsRedesign" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "needsRework" BOOLEAN NOT NULL DEFAULT false;
